# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- test

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: replacetokens@3
  inputs:
    rootDirectory: 'api'
    targetFiles: 'config.py'
    encoding: 'auto'
    writeBOM: true
    escapeType: 'none'
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '**'
    tokenSuffix: '**'
    useLegacyPattern: false
    enableTelemetry: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './'
    ArtifactName: 'obis_api'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
